import { useState, useEffect } from 'react';
import { WebContainer, FileSystemTree } from '@webcontainer/api';
// @ts-expect-error - virtual module generated by vite plugin
import { pokBundleFiles } from 'virtual:pok-bundle';

type WebContainerStatus = 'booting' | 'installing' | 'ready' | 'error';

interface UseWebContainerResult {
  webContainer: WebContainer | null;
  status: WebContainerStatus;
  error: Error | null;
}

// Singleton pattern to ensure only one WebContainer instance
let webContainerInstance: WebContainer | null = null;
let webContainerPromise: Promise<WebContainer> | null = null;

async function getWebContainer(): Promise<WebContainer> {
  if (webContainerInstance) {
    return webContainerInstance;
  }

  if (webContainerPromise) {
    return webContainerPromise;
  }

  webContainerPromise = WebContainer.boot();
  webContainerInstance = await webContainerPromise;
  return webContainerInstance;
}

/**
 * Convert flat file paths to WebContainer's nested FileSystemTree format.
 *
 * Takes an object like:
 *   { 'node_modules/@openpok/core/dist/index.js': '...' }
 *
 * And converts to:
 *   { 'node_modules': { directory: { '@openpok': { directory: { ... } } } } }
 */
function createFileSystemTree(files: Record<string, string>): FileSystemTree {
  const tree: FileSystemTree = {};

  for (const [filePath, contents] of Object.entries(files)) {
    const parts = filePath.split('/');
    let current: FileSystemTree = tree;

    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i];
      if (!current[part]) {
        current[part] = { directory: {} };
      }
      const node = current[part];
      if ('directory' in node) {
        current = node.directory;
      }
    }

    const fileName = parts[parts.length - 1];
    current[fileName] = { file: { contents } };
  }

  return tree;
}

export function useWebContainer(): UseWebContainerResult {
  const [webContainer, setWebContainer] = useState<WebContainer | null>(null);
  const [status, setStatus] = useState<WebContainerStatus>('booting');
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    let isCancelled = false;

    async function initializeWebContainer() {
      try {
        // Boot WebContainer
        setStatus('booting');
        const container = await getWebContainer();

        if (isCancelled) return;

        // Mount pre-bundled pok packages
        setStatus('installing');

        // Convert the flat file map to WebContainer's FileSystemTree format
        const bundleTree = createFileSystemTree(pokBundleFiles as Record<string, string>);

        // Create the full filesystem tree including package.json
        const filesystemTree: FileSystemTree = {
          'package.json': {
            file: {
              contents: JSON.stringify(
                {
                  name: 'pok-playground',
                  type: 'module',
                  dependencies: {
                    '@openpok/core': '0.0.1',
                    '@openpok/reporter-clack': '0.0.1',
                    '@openpok/prompter-clack': '0.0.1',
                    zod: '3.24.0',
                    'fast-glob': '3.3.2',
                  },
                },
                null,
                2
              ),
            },
          },
          ...bundleTree,
        };

        await container.mount(filesystemTree);

        if (isCancelled) return;

        // No npm install needed - everything is pre-bundled!
        console.log('[WebContainer] Pre-bundled pok packages mounted successfully');

        setWebContainer(container);
        setStatus('ready');
      } catch (err) {
        if (isCancelled) return;
        console.error('WebContainer initialization failed:', err);
        setError(err instanceof Error ? err : new Error(String(err)));
        setStatus('error');
      }
    }

    initializeWebContainer();

    return () => {
      isCancelled = true;
    };
  }, []);

  return { webContainer, status, error };
}
