import { useState, useEffect, useCallback } from 'react';
import { WebContainer, FileSystemTree } from '@webcontainer/api';
// @ts-expect-error - virtual module generated by vite plugin
import { pokBundleFiles } from 'virtual:pok-bundle';

type WebContainerStatus = 'booting' | 'installing' | 'ready' | 'error';

interface UseWebContainerResult {
  webContainer: WebContainer | null;
  status: WebContainerStatus;
  error: Error | null;
  retry: () => void;
}

// Singleton pattern to ensure only one WebContainer instance
let webContainerInstance: WebContainer | null = null;
let webContainerPromise: Promise<WebContainer> | null = null;
let mountPromise: Promise<void> | null = null;

/**
 * Get or create the WebContainer singleton instance.
 * Uses a singleton to prevent multiple container boots.
 */
async function getWebContainer(signal?: AbortSignal): Promise<WebContainer> {
  // Check for abort before starting
  if (signal?.aborted) {
    throw new DOMException('Aborted', 'AbortError');
  }

  if (webContainerInstance) {
    return webContainerInstance;
  }

  if (webContainerPromise) {
    return webContainerPromise;
  }

  console.log('[WebContainer] Booting new instance...');
  webContainerPromise = WebContainer.boot();
  webContainerInstance = await webContainerPromise;
  mountPromise = null; // Reset mount promise for new instance
  return webContainerInstance;
}

/**
 * Convert flat file paths to WebContainer's nested FileSystemTree format.
 *
 * Takes an object like:
 *   { 'node_modules/@openpok/core/dist/index.js': '...' }
 *
 * And converts to:
 *   { 'node_modules': { directory: { '@openpok': { directory: { ... } } } } }
 */
function createFileSystemTree(files: Record<string, string>): FileSystemTree {
  const tree: FileSystemTree = {};

  for (const [filePath, contents] of Object.entries(files)) {
    const parts = filePath.split('/');
    let current: FileSystemTree = tree;

    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i];
      if (!current[part]) {
        current[part] = { directory: {} };
      }
      const node = current[part];
      if ('directory' in node) {
        current = node.directory;
      }
    }

    const fileName = parts[parts.length - 1];
    current[fileName] = { file: { contents } };
  }

  return tree;
}

export function useWebContainer(): UseWebContainerResult {
  const [webContainer, setWebContainer] = useState<WebContainer | null>(null);
  const [status, setStatus] = useState<WebContainerStatus>('booting');
  const [error, setError] = useState<Error | null>(null);
  const [retryCount, setRetryCount] = useState(0);

  // Allow retry from error state
  const retry = useCallback(() => {
    setError(null);
    setStatus('booting');
    setRetryCount((c) => c + 1);
  }, []);

  useEffect(() => {
    const abortController = new AbortController();
    const signal = abortController.signal;

    async function initializeWebContainer() {
      try {
        // Boot WebContainer
        setStatus('booting');
        const container = await getWebContainer(signal);

        if (signal.aborted) return;

        // Mount pre-bundled pok packages
        setStatus('installing');

        // Only mount once - use singleton promise to prevent double-mounting
        if (mountPromise) {
          console.log('[WebContainer] Already mounting, waiting...');
          await mountPromise;
          setWebContainer(container);
          setStatus('ready');
          return;
        }

        // Convert the flat file map to WebContainer's FileSystemTree format
        const bundleTree = createFileSystemTree(pokBundleFiles as Record<string, string>);
        console.log('[WebContainer] Bundle tree keys:', Object.keys(bundleTree));

        // Create the full filesystem tree including package.json, pok.config.ts, and commands/
        const filesystemTree: FileSystemTree = {
          'package.json': {
            file: {
              contents: JSON.stringify(
                {
                  name: 'pok-tutorial',
                  type: 'module',
                  dependencies: {
                    '@openpok/core': '0.0.1',
                    '@openpok/reporter-clack': '0.0.1',
                    '@openpok/prompter-clack': '0.0.1',
                    '@openpok/introspect': '0.0.1',
                    zod: '3.24.0',
                    'fast-glob': '3.3.2',
                    'cli-highlight': '2.1.11',
                  },
                },
                null,
                2
              ),
            },
          },
          'pok.config.ts': {
            file: {
              contents: `// pok configuration for the interactive tutorial
export default {};
`,
            },
          },
          commands: {
            directory: {
              'introspect.ts': {
                file: {
                  contents: `// Re-export the introspect command from @openpok/introspect
const { command } = require('@openpok/introspect');
exports.command = command;
`,
                },
              },
              'learn.ts': {
                file: {
                  contents: `const { defineCommand } = require('@openpok/core');
const { writeFileSync, mkdirSync, existsSync } = require('fs');
const { execSync } = require('child_process');

const sleep = (ms) => new Promise(r => setTimeout(r, ms));

const HELLO_CODE = \`const { defineCommand } = require('@openpok/core');

exports.command = defineCommand({
  label: 'Say hello',
  run: async (r) => {
    r.reporter.success('Hello!');
  },
});
\`;

const GREET_CODE = \`const { z } = require('zod');
const { defineCommand } = require('@openpok/core');

exports.command = defineCommand({
  label: 'Greet someone',
  context: {
    name: {
      from: 'flag',
      schema: z.string(),
    },
  },
  run: async (r, { context }) => {
    r.reporter.success(\\\`Hello, \\\${context.name}!\\\`);
  },
});
\`;

const DEV_CODE = \`const { defineCommand } = require('@openpok/core');

exports.command = defineCommand({
  label: 'Development servers',
  run: async (r) => {
    await r.tabs([
      r.exec('npm run server'),
      r.exec('npm run watch'),
    ]);
  },
});
\`;

function printBox(r, filename, code) {
  const lines = code.trim().split('\\n');
  const width = 50;
  const padding = width - filename.length - 4;
  
  r.reporter.info('\\u250c\\u2500 ' + filename + ' ' + '\\u2500'.repeat(padding) + '\\u2510');
  r.reporter.info('\\u2502' + ' '.repeat(width) + '\\u2502');
  for (const line of lines) {
    const padded = '  ' + line;
    r.reporter.info('\\u2502' + padded.slice(0, width).padEnd(width) + '\\u2502');
  }
  r.reporter.info('\\u2502' + ' '.repeat(width) + '\\u2502');
  r.reporter.info('\\u2514' + '\\u2500'.repeat(width + 2) + '\\u2518');
}

exports.command = defineCommand({
  label: 'Learn pok interactively',
  run: async (r) => {
    if (!existsSync('commands')) {
      mkdirSync('commands');
    }

    while (true) {
      const choice = await r.prompter.select({
        message: 'What do you want to see?',
        options: [
          { value: 'create', label: 'Create a command' },
          { value: 'args', label: 'Add arguments' },
          { value: 'tabs', label: 'See tabs' },
          { value: 'exit', label: 'Explore freely' },
        ],
      });

      if (choice === 'exit') {
        r.reporter.info('');
        r.reporter.info('Your commands are in ./commands');
        r.reporter.info('');
        r.reporter.info('Try:');
        r.reporter.info('  pok         - see all commands');
        r.reporter.info('  pok hello   - run hello command');
        r.reporter.info('  pok --help  - see options');
        r.reporter.info('');
        break;
      }

      r.reporter.info('');

      if (choice === 'create') {
        r.reporter.info('Creating commands/hello.ts...');
        r.reporter.info('');
        
        writeFileSync('commands/hello.ts', HELLO_CODE);
        
        printBox(r, 'commands/hello.ts', HELLO_CODE);
        
        r.reporter.info('');
        r.reporter.info('Running: pok hello');
        r.reporter.info('');
        
        await sleep(300);
        
        try {
          execSync('node_modules/.bin/pok hello', { 
            stdio: 'inherit',
            cwd: process.cwd()
          });
        } catch (e) {
          // Command output already shown
        }
        
        r.reporter.info('');
        r.reporter.info('Done. You just saw a command created and executed.');
      }

      if (choice === 'args') {
        r.reporter.info('Creating commands/greet.ts...');
        r.reporter.info('');
        
        writeFileSync('commands/greet.ts', GREET_CODE);
        
        printBox(r, 'commands/greet.ts', GREET_CODE);
        
        r.reporter.info('');
        r.reporter.info('Running: pok greet --name World');
        r.reporter.info('');
        
        await sleep(300);
        
        try {
          execSync('node_modules/.bin/pok greet --name World', { 
            stdio: 'inherit',
            cwd: process.cwd()
          });
        } catch (e) {
          // Command output already shown
        }
        
        r.reporter.info('');
        r.reporter.info('Done. Flags become context. Schema validates them.');
      }

      if (choice === 'tabs') {
        r.reporter.info('Tabs run multiple processes side by side.');
        r.reporter.info('');
        
        printBox(r, 'commands/dev.ts', DEV_CODE);
        
        r.reporter.info('');
        r.reporter.info('In a real terminal, this opens a tabbed interface.');
        r.reporter.info('Each tab shows its process output.');
        r.reporter.info('Switch with <- ->, quit with q.');
        r.reporter.info('');
        r.reporter.warn("(Can't demo in browser - tabs need a real terminal.)");
      }

      r.reporter.info('');
      await sleep(500);
    }
  },
});
`,
                },
              },
            },
          },
          ...bundleTree,
        };

        console.log('[WebContainer] Filesystem tree top-level keys:', Object.keys(filesystemTree));

        mountPromise = container.mount(filesystemTree);
        await mountPromise;

        if (signal.aborted) return;

        // Make the pok binary executable
        console.log('[WebContainer] Making pok binary executable...');
        const chmodProcess = await container.spawn('chmod', ['+x', 'node_modules/.bin/pok']);
        await chmodProcess.exit;

        // No npm install needed - everything is pre-bundled!
        console.log('[WebContainer] Pre-bundled pok packages mounted successfully');

        setWebContainer(container);
        setStatus('ready');
      } catch (err) {
        if (signal.aborted) return;
        // Don't treat abort errors as failures
        if (err instanceof DOMException && err.name === 'AbortError') return;

        console.error('WebContainer initialization failed:', err);
        setError(err instanceof Error ? err : new Error(String(err)));
        setStatus('error');
      }
    }

    initializeWebContainer();

    return () => {
      abortController.abort();
    };
  }, [retryCount]);

  return { webContainer, status, error, retry };
}
