import { useState, useEffect, useCallback } from 'react';
import { WebContainer, FileSystemTree } from '@webcontainer/api';
// @ts-expect-error - virtual module generated by vite plugin
import { pokBundleFiles } from 'virtual:pok-bundle';

type WebContainerStatus = 'booting' | 'installing' | 'ready' | 'error';

interface UseWebContainerResult {
  webContainer: WebContainer | null;
  status: WebContainerStatus;
  error: Error | null;
  retry: () => void;
}

// Singleton pattern to ensure only one WebContainer instance
let webContainerInstance: WebContainer | null = null;
let webContainerPromise: Promise<WebContainer> | null = null;
let mountPromise: Promise<void> | null = null;

/**
 * Get or create the WebContainer singleton instance.
 * Uses a singleton to prevent multiple container boots.
 */
async function getWebContainer(signal?: AbortSignal): Promise<WebContainer> {
  // Check for abort before starting
  if (signal?.aborted) {
    throw new DOMException('Aborted', 'AbortError');
  }

  if (webContainerInstance) {
    return webContainerInstance;
  }

  if (webContainerPromise) {
    return webContainerPromise;
  }

  console.log('[WebContainer] Booting new instance...');
  webContainerPromise = WebContainer.boot();
  webContainerInstance = await webContainerPromise;
  mountPromise = null; // Reset mount promise for new instance
  return webContainerInstance;
}

/**
 * Convert flat file paths to WebContainer's nested FileSystemTree format.
 *
 * Takes an object like:
 *   { 'node_modules/@openpok/core/dist/index.js': '...' }
 *
 * And converts to:
 *   { 'node_modules': { directory: { '@openpok': { directory: { ... } } } } }
 */
function createFileSystemTree(files: Record<string, string>): FileSystemTree {
  const tree: FileSystemTree = {};

  for (const [filePath, contents] of Object.entries(files)) {
    const parts = filePath.split('/');
    let current: FileSystemTree = tree;

    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i];
      if (!current[part]) {
        current[part] = { directory: {} };
      }
      const node = current[part];
      if ('directory' in node) {
        current = node.directory;
      }
    }

    const fileName = parts[parts.length - 1];
    current[fileName] = { file: { contents } };
  }

  return tree;
}

export function useWebContainer(): UseWebContainerResult {
  const [webContainer, setWebContainer] = useState<WebContainer | null>(null);
  const [status, setStatus] = useState<WebContainerStatus>('booting');
  const [error, setError] = useState<Error | null>(null);
  const [retryCount, setRetryCount] = useState(0);

  // Allow retry from error state
  const retry = useCallback(() => {
    setError(null);
    setStatus('booting');
    setRetryCount((c) => c + 1);
  }, []);

  useEffect(() => {
    const abortController = new AbortController();
    const signal = abortController.signal;

    async function initializeWebContainer() {
      try {
        // Boot WebContainer
        setStatus('booting');
        const container = await getWebContainer(signal);

        if (signal.aborted) return;

        // Mount pre-bundled pok packages
        setStatus('installing');

        // Only mount once - use singleton promise to prevent double-mounting
        if (mountPromise) {
          console.log('[WebContainer] Already mounting, waiting...');
          await mountPromise;
          setWebContainer(container);
          setStatus('ready');
          return;
        }

        // Convert the flat file map to WebContainer's FileSystemTree format
        const bundleTree = createFileSystemTree(pokBundleFiles as Record<string, string>);
        console.log('[WebContainer] Bundle tree keys:', Object.keys(bundleTree));

        // Create the full filesystem tree including package.json, pok.config.ts, and commands/
        const filesystemTree: FileSystemTree = {
          'package.json': {
            file: {
              contents: JSON.stringify(
                {
                  name: 'pok-tutorial',
                  type: 'module',
                  dependencies: {
                    '@openpok/core': '0.0.1',
                    '@openpok/reporter-clack': '0.0.1',
                    '@openpok/prompter-clack': '0.0.1',
                    zod: '3.24.0',
                    'fast-glob': '3.3.2',
                  },
                },
                null,
                2
              ),
            },
          },
          'pok.config.ts': {
            file: {
              contents: `// pok configuration for the interactive tutorial
export default {};
`,
            },
          },
          commands: {
            directory: {
              'learn.ts': {
                file: {
                  contents: `const { defineCommand } = require('@openpok/core');
const { writeFileSync, readFileSync } = require('fs');

exports.command = defineCommand({
  label: 'Learn pok interactively',
  run: async (r) => {
    r.reporter.step('Welcome to pok!');
    r.reporter.info('');
    r.reporter.info('This interactive tutorial will guide you through learning pok,');
    r.reporter.info('a modern CLI framework for building developer tools.');
    r.reporter.info('');

    while (true) {
      const choice = await r.prompter.select({
        message: 'What would you like to learn?',
        options: [
          { value: 'first', label: 'Your first command' },
          { value: 'args', label: 'Arguments and flags' },
          { value: 'tabs', label: 'Tabs (multi-process)' },
          { value: 'source', label: 'How was this made?' },
          { value: 'exit', label: 'Free exploration' },
        ],
      });

      if (choice === 'exit') {
        r.reporter.info('');
        r.reporter.success('Have fun exploring!');
        r.reporter.info('');
        r.reporter.info('Try these commands:');
        r.reporter.info('  pok --help     Show available commands');
        r.reporter.info('  pok learn      Return to this tutorial');
        r.reporter.info('');
        break;
      }

      // ========================================
      // LESSON 3: How was this made?
      // ========================================
      if (choice === 'source') {
        r.reporter.info('');
        r.reporter.step('How was this made?');
        r.reporter.info('');
        r.reporter.info('This tutorial is itself a pok command!');
        r.reporter.info('');
        r.reporter.info('It uses:');
        r.reporter.info('  - defineCommand() to define the learn command');
        r.reporter.info('  - r.prompter.select() for interactive menus');
        r.reporter.info('  - r.reporter.info/success/step() for styled output');
        r.reporter.info('  - A while(true) loop to keep the menu running');
        r.reporter.info('');
        r.reporter.info("Let me show you the actual source code...");
        r.reporter.info('');

        try {
          const source = readFileSync('commands/learn.ts', 'utf-8');
          r.reporter.info('--- commands/learn.ts ---');
          r.reporter.info('');
          const lines = source.split('\\n').slice(0, 40);
          for (const line of lines) {
            r.reporter.info(line);
          }
          if (source.split('\\n').length > 40) {
            r.reporter.info('');
            r.reporter.info('... (truncated - file continues)');
          }
          r.reporter.info('');
          r.reporter.info('--- end of file ---');
        } catch (e) {
          r.reporter.warn('Could not read source file');
        }

        r.reporter.info('');
        r.reporter.info('Key concepts used in this tutorial:');
        r.reporter.info('');
        r.reporter.info('  1. defineCommand() - creates the command');
        r.reporter.info('  2. r.reporter.info/success/step() - structured output');
        r.reporter.info('  3. r.prompter.select() - interactive menus');
        r.reporter.info('  4. r.prompter.confirm() - yes/no prompts');
        r.reporter.info('  5. fs.writeFileSync() - create files');
        r.reporter.info('  6. fs.readFileSync() - read files (like this source!)');
        r.reporter.info('');
        r.reporter.info('Want to learn more? Check out the pok repository:');
        r.reporter.info('  https://github.com/notation/pok');
        r.reporter.info('');

        await r.prompter.confirm({ message: 'Back to menu?' });
        continue;
      }

      // ========================================
      // LESSON 1: Your First Command
      // ========================================
      if (choice === 'first') {
        r.reporter.info('');
        r.reporter.step('Lesson 1: Your First Command');
        r.reporter.info('');
        r.reporter.info('Commands in pok are TypeScript files in the commands/ directory.');
        r.reporter.info('Each file exports a command using defineCommand().');
        r.reporter.info('');
        r.reporter.info('A command has two main parts:');
        r.reporter.info('  - label: A description shown in help');
        r.reporter.info('  - run: The function that executes when the command runs');
        r.reporter.info('');

        await r.prompter.confirm({ message: 'Ready to see an example?' });

        r.reporter.info('');
        r.reporter.info("Here's a simple \\"hello\\" command:");
        r.reporter.info('');
        r.reporter.info("  const { defineCommand } = require('@openpok/core');");
        r.reporter.info('');
        r.reporter.info('  exports.command = defineCommand({');
        r.reporter.info("    label: 'Say hello to the world',");
        r.reporter.info('    run: async (r) => {');
        r.reporter.info("      r.reporter.success('Hello, world!');");
        r.reporter.info('    },');
        r.reporter.info('  });');
        r.reporter.info('');

        const createIt = await r.prompter.select({
          message: 'Would you like me to create this command for you?',
          options: [
            { value: 'yes', label: 'Yes, create commands/hello.ts' },
            { value: 'no', label: 'No, I\\'ll do it myself' },
          ],
        });

        if (createIt === 'yes') {
          const helloCode = \`const { defineCommand } = require('@openpok/core');

exports.command = defineCommand({
  label: 'Say hello to the world',
  run: async (r) => {
    r.reporter.success('Hello, world!');
  },
});
\`;
          writeFileSync('commands/hello.ts', helloCode);
          r.reporter.info('');
          r.reporter.success('Created commands/hello.ts');
          r.reporter.info('');
          r.reporter.info('Now try running it! Exit this tutorial and type:');
          r.reporter.info('');
          r.reporter.info('  pok hello');
          r.reporter.info('');

          const runNow = await r.prompter.confirm({ 
            message: 'Exit tutorial to try it now?' 
          });

          if (runNow) {
            r.reporter.info('');
            r.reporter.success('Great! Type "pok hello" to run your command.');
            r.reporter.info('Then run "pok learn" to continue learning.');
            r.reporter.info('');
            break;
          }
        } else {
          r.reporter.info('');
          r.reporter.info('No problem! Create the file yourself:');
          r.reporter.info('  1. Create commands/hello.ts');
          r.reporter.info('  2. Add the code shown above');
          r.reporter.info('  3. Run: pok hello');
          r.reporter.info('');
          await r.prompter.confirm({ message: 'Back to menu?' });
        }
        continue;
      }

      // ========================================
      // LESSON 2: Arguments and Flags
      // ========================================
      if (choice === 'args') {
        r.reporter.info('');
        r.reporter.step('Lesson 2: Arguments and Flags');
        r.reporter.info('');
        r.reporter.info('Commands become more useful when they accept input.');
        r.reporter.info('pok supports arguments and flags via the "args" property.');
        r.reporter.info('');
        r.reporter.info('Each argument is defined with:');
        r.reporter.info('  - type: string, number, or boolean');
        r.reporter.info('  - description: shown in --help');
        r.reporter.info('  - required: whether it must be provided');
        r.reporter.info('');

        await r.prompter.confirm({ message: 'Ready to see an example?' });

        r.reporter.info('');
        r.reporter.info("Here's a \\"greet\\" command that takes a name:");
        r.reporter.info('');
        r.reporter.info("  const { z } = require('zod');");
        r.reporter.info("  const { defineCommand } = require('@openpok/core');");
        r.reporter.info('');
        r.reporter.info('  exports.command = defineCommand({');
        r.reporter.info("    label: 'Greet someone by name',");
        r.reporter.info('    context: {');
        r.reporter.info('      name: {');
        r.reporter.info("        from: 'flag',");
        r.reporter.info('        schema: z.string(),');
        r.reporter.info("        description: 'Name of the person to greet',");
        r.reporter.info('      },');
        r.reporter.info('      shout: {');
        r.reporter.info("        from: 'flag',");
        r.reporter.info('        schema: z.boolean().default(false),');
        r.reporter.info("        description: 'Greet loudly in uppercase',");
        r.reporter.info('      },');
        r.reporter.info('    },');
        r.reporter.info('    run: async (r, { context }) => {');
        r.reporter.info("      let greeting = \\\`Hello, \\\${context.name}!\\\`;");
        r.reporter.info('      if (context.shout) greeting = greeting.toUpperCase();');
        r.reporter.info('      r.reporter.success(greeting);');
        r.reporter.info('    },');
        r.reporter.info('  });');
        r.reporter.info('');

        const createIt = await r.prompter.select({
          message: 'Would you like me to create this command?',
          options: [
            { value: 'yes', label: 'Yes, create commands/greet.ts' },
            { value: 'no', label: 'No, I\\'ll explore on my own' },
          ],
        });

        if (createIt === 'yes') {
          const greetCode = \`const { z } = require('zod');
const { defineCommand } = require('@openpok/core');

exports.command = defineCommand({
  label: 'Greet someone by name',
  context: {
    name: {
      from: 'flag',
      schema: z.string(),
      description: 'Name of the person to greet',
    },
    shout: {
      from: 'flag',
      schema: z.boolean().default(false),
      description: 'Greet loudly in uppercase',
    },
  },
  run: async (r, { context }) => {
    let greeting = \\\`Hello, \\\${context.name}!\\\`;
    if (context.shout) greeting = greeting.toUpperCase();
    r.reporter.success(greeting);
  },
});
\`;
          writeFileSync('commands/greet.ts', greetCode);
          r.reporter.info('');
          r.reporter.success('Created commands/greet.ts');
          r.reporter.info('');
          r.reporter.info('Try running it with different arguments:');
          r.reporter.info('');
          r.reporter.info('  pok greet --name Alice');
          r.reporter.info('  pok greet --name Bob --shout');
          r.reporter.info('  pok greet --help');
          r.reporter.info('');

          const runNow = await r.prompter.confirm({ 
            message: 'Exit tutorial to try it?' 
          });

          if (runNow) {
            r.reporter.info('');
            r.reporter.success('Go ahead! Try: pok greet --name Alice');
            r.reporter.info('Run "pok learn" to return to this tutorial.');
            r.reporter.info('');
            break;
          }
        } else {
          r.reporter.info('');
          r.reporter.info('Feel free to experiment! Remember:');
          r.reporter.info('  - Args are passed as --name value or --flag');
          r.reporter.info('  - Use --help to see available arguments');
          r.reporter.info('');
          await r.prompter.confirm({ message: 'Back to menu?' });
        }
        continue;
      }

      // ========================================
      // LESSON: Tabs (Multi-Process)
      // ========================================
      if (choice === 'tabs') {
        r.reporter.info('');
        r.reporter.step('Tabs: Multi-Process Management');
        r.reporter.info('');
        r.reporter.info('Pok can run multiple processes in a tabbed terminal interface.');
        r.reporter.info('Each tab shows its own output, and you can switch between them.');
        r.reporter.info('');
        r.reporter.info('This is perfect for development workflows like:');
        r.reporter.info('  - Running a dev server + file watcher');
        r.reporter.info('  - Running tests + linter simultaneously');
        r.reporter.info('  - Database + API server + frontend dev server');
        r.reporter.info('');

        await r.prompter.confirm({ message: 'Ready to see how it works?' });

        r.reporter.info('');
        r.reporter.info("Here's a command that launches three tabs:");
        r.reporter.info('');
        r.reporter.info("  const { defineCommand } = require('@openpok/core');");
        r.reporter.info('');
        r.reporter.info('  exports.command = defineCommand({');
        r.reporter.info("    label: 'Start development servers',");
        r.reporter.info('    run: async (r) => {');
        r.reporter.info('      await r.tabs([');
        r.reporter.info("        r.exec('npm run dev'),");
        r.reporter.info("        r.exec('npm run watch:css'),");
        r.reporter.info("        r.exec('stripe listen'),");
        r.reporter.info("      ], { name: 'Development' });");
        r.reporter.info('    },');
        r.reporter.info('  });');
        r.reporter.info('');

        await r.prompter.confirm({ message: 'Continue?' });

        r.reporter.info('');
        r.reporter.info('When running tabs, you can:');
        r.reporter.info('  - Use arrow keys (<- ->) to switch between tabs');
        r.reporter.info('  - Scroll through each tab\\'s output');
        r.reporter.info('  - See status indicators (running/done/error)');
        r.reporter.info('  - Press q to quit all processes');
        r.reporter.info('');
        r.reporter.info('You can also use tasks with tabs:');
        r.reporter.info('');
        r.reporter.info('  await r.tabs([');
        r.reporter.info('    r.run(devServerTask),');
        r.reporter.info('    r.run(watcherTask),');
        r.reporter.info("    r.exec('stripe listen'),");
        r.reporter.info('  ]);');
        r.reporter.info('');

        await r.prompter.confirm({ message: 'Continue?' });

        r.reporter.info('');
        r.reporter.step('Setup Required');
        r.reporter.info('');
        r.reporter.info('To use tabs, you need to configure a tabs adapter.');
        r.reporter.info('Add this to your pok.config.ts:');
        r.reporter.info('');
        r.reporter.info("  import { createRouter } from '@openpok/core';");
        r.reporter.info("  import { createTabsAdapter } from '@openpok/tabs-ink';");
        r.reporter.info('');
        r.reporter.info('  export default createRouter({');
        r.reporter.info('    tabs: createTabsAdapter(),');
        r.reporter.info('  });');
        r.reporter.info('');
        r.reporter.info('Then install the package:');
        r.reporter.info('');
        r.reporter.info('  npm install @openpok/tabs-ink');
        r.reporter.info('');

        r.reporter.info('');
        r.reporter.warn('Note: Tabs require a real terminal (TUI) and cannot');
        r.reporter.warn('be demonstrated in this browser-based tutorial.');
        r.reporter.info('');
        r.reporter.info('Try tabs locally by cloning the pok repository:');
        r.reporter.info('  https://github.com/notation/pok');
        r.reporter.info('');

        await r.prompter.confirm({ message: 'Back to menu?' });
        continue;
      }
    }
  },
});
`,
                },
              },
            },
          },
          ...bundleTree,
        };

        console.log('[WebContainer] Filesystem tree top-level keys:', Object.keys(filesystemTree));

        mountPromise = container.mount(filesystemTree);
        await mountPromise;

        if (signal.aborted) return;

        // Make the pok binary executable
        console.log('[WebContainer] Making pok binary executable...');
        const chmodProcess = await container.spawn('chmod', ['+x', 'node_modules/.bin/pok']);
        await chmodProcess.exit;

        // No npm install needed - everything is pre-bundled!
        console.log('[WebContainer] Pre-bundled pok packages mounted successfully');

        setWebContainer(container);
        setStatus('ready');
      } catch (err) {
        if (signal.aborted) return;
        // Don't treat abort errors as failures
        if (err instanceof DOMException && err.name === 'AbortError') return;

        console.error('WebContainer initialization failed:', err);
        setError(err instanceof Error ? err : new Error(String(err)));
        setStatus('error');
      }
    }

    initializeWebContainer();

    return () => {
      abortController.abort();
    };
  }, [retryCount]);

  return { webContainer, status, error, retry };
}
