import { useState, useEffect, useCallback } from 'react';
import { WebContainer, FileSystemTree } from '@webcontainer/api';
// @ts-expect-error - virtual module generated by vite plugin
import { pokBundleFiles } from 'virtual:pok-bundle';
// Import learn command as raw string for WebContainer filesystem
import learnCommandCode from '../commands/learn.ts?raw';

type WebContainerStatus = 'booting' | 'installing' | 'ready' | 'error';

interface UseWebContainerResult {
  webContainer: WebContainer | null;
  status: WebContainerStatus;
  error: Error | null;
  retry: () => void;
}

// Singleton pattern to ensure only one WebContainer instance
let webContainerInstance: WebContainer | null = null;
let webContainerPromise: Promise<WebContainer> | null = null;
let mountPromise: Promise<void> | null = null;

/**
 * Get or create the WebContainer singleton instance.
 * Uses a singleton to prevent multiple container boots.
 */
async function getWebContainer(signal?: AbortSignal): Promise<WebContainer> {
  // Check for abort before starting
  if (signal?.aborted) {
    throw new DOMException('Aborted', 'AbortError');
  }

  if (webContainerInstance) {
    return webContainerInstance;
  }

  if (webContainerPromise) {
    return webContainerPromise;
  }

  console.log('[WebContainer] Booting new instance...');
  webContainerPromise = WebContainer.boot();
  webContainerInstance = await webContainerPromise;
  mountPromise = null; // Reset mount promise for new instance
  return webContainerInstance;
}

/**
 * Convert flat file paths to WebContainer's nested FileSystemTree format.
 *
 * Takes an object like:
 *   { 'node_modules/@openpok/core/dist/index.js': '...' }
 *
 * And converts to:
 *   { 'node_modules': { directory: { '@openpok': { directory: { ... } } } } }
 */
function createFileSystemTree(files: Record<string, string>): FileSystemTree {
  const tree: FileSystemTree = {};

  for (const [filePath, contents] of Object.entries(files)) {
    const parts = filePath.split('/');
    let current: FileSystemTree = tree;

    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i];
      if (!current[part]) {
        current[part] = { directory: {} };
      }
      const node = current[part];
      if ('directory' in node) {
        current = node.directory;
      }
    }

    const fileName = parts[parts.length - 1];
    current[fileName] = { file: { contents } };
  }

  return tree;
}

export function useWebContainer(): UseWebContainerResult {
  const [webContainer, setWebContainer] = useState<WebContainer | null>(null);
  const [status, setStatus] = useState<WebContainerStatus>('booting');
  const [error, setError] = useState<Error | null>(null);
  const [retryCount, setRetryCount] = useState(0);

  // Allow retry from error state
  const retry = useCallback(() => {
    setError(null);
    setStatus('booting');
    setRetryCount((c) => c + 1);
  }, []);

  useEffect(() => {
    const abortController = new AbortController();
    const signal = abortController.signal;

    async function initializeWebContainer() {
      try {
        // Boot WebContainer
        setStatus('booting');
        const container = await getWebContainer(signal);

        if (signal.aborted) return;

        // Mount pre-bundled pok packages
        setStatus('installing');

        // Only mount once - use singleton promise to prevent double-mounting
        if (mountPromise) {
          console.log('[WebContainer] Already mounting, waiting...');
          await mountPromise;
          setWebContainer(container);
          setStatus('ready');
          return;
        }

        // Convert the flat file map to WebContainer's FileSystemTree format
        const bundleTree = createFileSystemTree(pokBundleFiles as Record<string, string>);
        console.log('[WebContainer] Bundle tree keys:', Object.keys(bundleTree));

        // Create the full filesystem tree including package.json, pok.config.ts, and commands/
        const filesystemTree: FileSystemTree = {
          'package.json': {
            file: {
              contents: JSON.stringify(
                {
                  name: 'pok-tutorial',
                  type: 'module',
                  dependencies: {
                    '@openpok/core': '0.0.1',
                    '@openpok/reporter-clack': '0.0.1',
                    '@openpok/prompter-clack': '0.0.1',
                    zod: '3.24.0',
                    'fast-glob': '3.3.2',
                  },
                },
                null,
                2
              ),
            },
          },
          'pok.config.ts': {
            file: {
              contents: `// pok configuration for the interactive tutorial
export default {};
`,
            },
          },
          commands: {
            directory: {
              'learn.ts': {
                file: {
                  contents: learnCommandCode,
                },
              },
            },
          },
          ...bundleTree,
        };

        console.log('[WebContainer] Filesystem tree top-level keys:', Object.keys(filesystemTree));

        mountPromise = container.mount(filesystemTree);
        await mountPromise;

        if (signal.aborted) return;

        // Make the pok binary executable
        console.log('[WebContainer] Making pok binary executable...');
        const chmodProcess = await container.spawn('chmod', ['+x', 'node_modules/.bin/pok']);
        await chmodProcess.exit;

        // No npm install needed - everything is pre-bundled!
        console.log('[WebContainer] Pre-bundled pok packages mounted successfully');

        setWebContainer(container);
        setStatus('ready');
      } catch (err) {
        if (signal.aborted) return;
        // Don't treat abort errors as failures
        if (err instanceof DOMException && err.name === 'AbortError') return;

        console.error('WebContainer initialization failed:', err);
        setError(err instanceof Error ? err : new Error(String(err)));
        setStatus('error');
      }
    }

    initializeWebContainer();

    return () => {
      abortController.abort();
    };
  }, [retryCount]);

  return { webContainer, status, error, retry };
}
